### ISSUE TITLE
Class to async download and manage data structure of building info

### ISSUE THREAD

**Issue by ethantanner** [AugustanaCSC490Spring2015/GradliciousVikingHub#1]

**Comment by daviddevore11** [comment]
I have created the class BuildingSharedPreferences that will pull all of the academic building's from parse and put them into a SharedPreference.  The building names are the keys that are matched with one string that contains all of the data for the building, seperated by a ";".  For example Olin will be entered in the sharedPreferences by ("Olin", "Thu May 07 12:01:15 CDT 2015;Opened: 1998;Majors: Computer Science and Mathematics;Contains an Auditorium and computer labs;Groups Located Here: EDGE and CORE").  It will be exteremly easy to parse through the long data string.  All that will be needed is the split method by sending in ";" as the param, .split(";").  That should create a String array of all of the relevant info for that building.  The update feature has yet to be tested.

**Comment by fstonedahl** [comment]
Why put them in a SharedPreferences object?

I doubt that makes sense... if you are pulling from Parse, you can just use Parse's local caching features to keep all of the data locally, and avoid all of the conversion into a different local phone storage format!
