### ISSUE TITLE
EventsCalendar.java will not compile

### ISSUE THREAD

**Issue by ethantanner** [AugustanaCSC490Spring2015/GradliciousVikingHub#5]
The import of jsoup is causing the issue. I commented out the class and the intent in MainActivity.

**Comment by ashearouse** [comment]
It was compiling correctly for me, so my guess is that somehow the .jar file didn't push with the rest of the app. If so, it should be a quick fix...but I won't be able to make that change until I'm at an on-campus computer, because my laptop can't run Android Studio.

**Comment by fstonedahl** [comment]
That could be the issue.  if you added a new file  (e.g. a library JAR file), you need to remember to "git->add" it before "commit" and "push".  

You should be able to browse the files on GitHub, to see whether the JAR file is there or not.
